const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const cp=require('node:child_process');
const C=require('./core');
// v0.1 regression fixtures retain their original continuous-layout settings.
const B={...C,layout:(text,p={})=>C.layout(text,{layoutMode:'continuous',top:20,bottom:20,left:20,right:20,...p})};
let count=0;
function test(name,fn){fn();count++;console.log('PASS',name);}
test('ASCII A = 1000001; exact count',()=>{assert.equal(B.ascii('A'),'1000001');const r=B.layout('A');assert.equal(r.holes.length,2);assert.equal(r.holes[0].x,21.605);assert.ok(Math.abs(r.holes[1].x-45.305)<1e-9);});
test('ASCII full 0–127 range round trip',()=>{const s=Array.from({length:128},(_,i)=>String.fromCharCode(i)).join('');const bits=B.ascii(s);assert.equal(bits.length,896);assert.equal(bits.match(/.{7}/g).map(b=>String.fromCharCode(parseInt(b,2))).join(''),s);});
test('non-ASCII never silently changed',()=>{assert.throws(()=>B.ascii('한글'),/ASCII/);assert.throws(()=>B.ascii('😀'),/ASCII/);assert.equal(B.minify('// 한글\nvoid setup() {}'),'void setup(){}');});
test('include retains newline',()=>assert.equal(B.minify('#include <Servo.h>\nServo s;\nvoid setup() {s.attach(9);}'),'#include <Servo.h>\nServo s;void setup(){s.attach(9);}'));
test('comments inside literals remain intact',()=>{const s='const char* s="https://a/*b*/"; char c=\'\\\'\'; // remove\n';const m=B.minify(s);assert.ok(m.includes('"https://a/*b*/"'));assert.ok(!m.includes('remove'));});
test('raw strings and macro whitespace protected',()=>{const s='#define STR(x) #x\nconst char* p=STR(a + b);\nconst char* r=R"xx(//x\n/*y*/)xx";';assert.equal(B.minify(s),s);assert.equal(B.minify('auto a=STR(a + b);'),'auto a=STR(a + b);');});
test('operators and exponent tokens preserved',()=>{const s='int a = 1; int b = a + + a; double x = 1e+3; int c = a / *p;';const tokens=x=>B.lex(x).filter(t=>t.type!=='space'&&t.type!=='comment').map(t=>t.s);assert.deepEqual(tokens(B.minify(s)),tokens(s));});
test('unsupported/malformed inputs fail without output',()=>{for(const s of ['/* never ends','"never ends','a\\\nb',''])assert.throws(()=>B.minify(s));});
test('layout includes zero slots and wraps correctly',()=>{const r=B.layout('A',{width:10,height:16,left:1,right:1,top:1,bottom:1,diameter:2,gap:1,rowGap:1,stroke:.01});assert.equal(r.cols,2);assert.equal(r.rows,4);assert.equal(r.holes[1].x,r.holes[0].x);assert.equal(r.holes[1].y-r.holes[0].y,9);});
test('overflow blocks even trailing zero slots',()=>{assert.throws(()=>B.layout('\x00',{width:10,height:10,left:1,right:1,top:1,bottom:1,diameter:3,gap:1,rowGap:1}),/들어가지/);});
test('all stroke extents stay within asymmetric margins',()=>{const r=B.layout('ABC'.repeat(50),{width:300,height:450,left:13,right:27,top:11,bottom:33});const a=(r.p.diameter+r.p.stroke)/2;for(const h of r.holes){assert.ok(h.x-a>=13-1e-9);assert.ok(h.x+a<=273+1e-9);assert.ok(h.y-a>=11-1e-9);assert.ok(h.y+a<=417+1e-9);}});
test('invalid geometry/color rejected',()=>{for(const p of [{width:NaN},{height:Infinity},{top:-1},{diameter:0},{gap:0},{stroke:4},{color:'red"/><script>'},{left:300}])assert.throws(()=>B.layout('A',p));});
test('SVG mm, hairline, no guide objects',()=>{const svg=B.svg(B.layout('A'));assert.ok(svg.includes('width="300mm" height="450mm"'));assert.ok(svg.includes('stroke-width="0.01"'));assert.ok(svg.includes('fill="none"'));assert.equal((svg.match(/<circle /g)||[]).length,2);assert.ok(!svg.includes('<rect'));});
// Optional C++ behavior check: real compiler with minimal Arduino API stubs.
if(cp.spawnSync('g++',['--version']).status===0)test('original and minified C++ compile and execute identically',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bouchon-'));
 const prefix='#include <cstdio>\n#define OUTPUT 1\nvoid pinMode(int a,int b){printf("p%d,%d;",a,b);}\nvoid digitalWrite(int a,int b){printf("w%d,%d;",a,b);}\nvoid delay(int a){printf("d%d;",a);}\n';
 const cases=['void setup() { pinMode(13, OUTPUT); }\nvoid loop() {digitalWrite(13,1);delay(1000);digitalWrite(13,0);delay(1000);}', '#define STR(x) #x\nvoid setup(){puts(STR(a + b));}\nvoid loop(){}', 'void setup(){const char* s="http://a/*b*/"; puts(s); int a=1;printf("%d",a + + a);}\nvoid loop(){}'];
 try{for(const [i,s]of cases.entries()){let outputs=[];for(const [j,body]of [s,B.minify(s)].entries()){const file=path.join(dir,`${i}-${j}.cpp`),exe=path.join(dir,`${i}-${j}`);fs.writeFileSync(file,prefix+body+'\nint main(){setup();loop();}\n');cp.execFileSync('g++',['-std=c++11',file,'-o',exe]);outputs.push(cp.execFileSync(exe,{encoding:'utf8'}));}assert.deepEqual(outputs[0],outputs[1]);}}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('column is default; A bits run down one column',()=>{const r=C.layout('A');assert.equal(r.p.layoutMode,'column');assert.equal(r.cols,14);assert.equal(r.holes.length,2);assert.equal(r.holes[0].x,r.holes[1].x);assert.ok(Math.abs(r.holes[0].y-28)<1e-9);assert.ok(Math.abs(r.holes[1].y-r.holes[0].y-6*3.95)<1e-9);assert.ok(Math.abs(r.holes[0].x-(26+248/28))<1e-9);});
test('14th stays in group one; 15th wraps to group two',()=>{const r=C.layout('A'.repeat(15));const a=C.position(r,13*7),b=C.position(r,14*7);assert.equal(a.y,C.position(r,0).y);assert.equal(b.x,C.position(r,0).x);assert.ok(b.y>a.y);assert.ok(Math.abs(C.position(r,14*7+6).y+(3.2+.01)/2-420)<1e-8);});
test('manual pitches follow exact requested formula',()=>{const r=C.layout('A'.repeat(7),{charactersPerRow:3,columnSpacing:'manual',columnPitch:12,rowGroupSpacing:'manual',rowGroupPitch:32});assert.deepEqual(C.position(r,3*7),{x:32,y:60});assert.equal(C.position(r,2*7).x,56);assert.equal(r.rows,3);});
test('zeros reserve complete character columns without output',()=>{const r=C.layout('\x00A');assert.equal(r.holes.length,2);assert.equal(r.holes[0].x,C.position(r,7).x);assert.ok(!C.svg(C.layout('\x00')).includes('<circle'));});
test('column overflow never silently shrinks or clips',()=>{for(const p of [{width:50},{height:70},{columnSpacing:'manual',columnPitch:40},{rowGroupSpacing:'manual',rowGroupPitch:500}])assert.throws(()=>C.layout('A'.repeat(15),p));});
test('invalid counts, pitches and modes rejected',()=>{for(const p of [{charactersPerRow:0},{charactersPerRow:2.5},{charactersPerRow:Infinity},{bitPitch:1},{columnSpacing:'manual',columnPitch:1},{rowGroupSpacing:'manual',rowGroupPitch:1},{layoutMode:'unknown'},{columnSpacing:'unknown'}])assert.throws(()=>C.layout('A',p));});
test('all column centers and side/bottom extents respect configured bounds',()=>{for(const n of [1,14,15,28,100,196]){const r=C.layout('A'.repeat(n)),half=(r.p.diameter+r.p.stroke)/2;for(let i=0;i<r.bits.length;i++){const q=C.position(r,i);assert.ok(q.x-half>=26-1e-8);assert.ok(q.x+half<=274+1e-8);assert.ok(q.y>=28-1e-8);assert.ok(q.y+half<=420+1e-8);}}});
test('both modes output PDF stroke-only paths with matching hole count',()=>{for(const layoutMode of ['column','continuous']){const r=C.layout('AB',{layoutMode}),pdf=C.pdf(r);assert.ok(pdf.startsWith('%PDF-1.4'));assert.equal((pdf.match(/h S/g)||[]).length,r.holes.length);assert.ok(pdf.includes('0.01 w'));assert.ok(pdf.includes('1 0 0 RG'));assert.ok(!pdf.includes('/Image'));const offset=Number(/startxref\n(\d+)/.exec(pdf)[1]);assert.equal(pdf.slice(offset,offset+4),'xref');}});
test('void debug values and actual SVG columns match independently',()=>{
 const r=C.layout('void'),expected=[['v',118,'1110110'],['o',111,'1101111'],['i',105,'1101001'],['d',100,'1100100']];
 assert.deepEqual(r.characters.map(e=>[e.character,e.decimal,e.binary]),expected);
 const circles=[...C.svg(r).matchAll(/<circle cx="([^"]+)" cy="([^"]+)"/g)].map(m=>({x:Number(m[1]),y:Number(m[2])}));
 for(let j=0;j<4;j++){const x=26+(j+.5)*248/14;const actual=circles.filter(h=>Math.abs(h.x-x)<1e-7);const ys=[...expected[j][2]].flatMap((b,i)=>b==='1'?[28+i*3.95]:[]);assert.equal(actual.length,ys.length);actual.forEach((h,i)=>assert.ok(Math.abs(h.y-ys[i])<1e-7));}
 for(let j=0;j<4;j++)for(let bit=0;bit<7;bit++){assert.equal(C.columnPosition(r,j,bit).x,C.columnPosition(r,j,0).x);assert.equal(C.columnPosition(r,j,bit).y,28+bit*3.95);}
});
test('debug audit blocks corrupted columns in SVG and PDF',()=>{const r=C.layout('void');r.holes[1].x+=1;assert.throws(()=>C.svg(r),/불일치/);assert.throws(()=>C.pdf(r),/불일치/);const a=C.layout('void');a.characters[0].binary='0000000';assert.throws(()=>C.validateColumns(a),/불일치/);});
test('space/newline reserve one character each and index 14 wraps',()=>{const r=C.layout('void \n'+'v'.repeat(9));assert.equal(r.characters[4].decimal,32);assert.equal(r.characters[5].decimal,10);assert.equal(C.columnPosition(r,14,0).x,C.columnPosition(r,0,0).x);assert.equal(C.columnPosition(r,14,0).y,28+r.rowGroupPitch);});
test('SVG separators follow character groups including zero-only columns',()=>{for(const [text,n] of [['v'.repeat(14),1],['v'.repeat(15),2],['\x00'.repeat(15),2]]){const r=C.layout(text),s=C.svg(r);assert.equal((s.match(/<line /g)||[]).length,n);assert.ok(s.includes('id="row-group-separators"'));for(let i=1;i<=n;i++)assert.ok(s.includes(`id="row-separator-${i}"`));}assert.equal(C.separators(C.layout('v'.repeat(15),{charactersPerRow:5})).lines.length,3);});
test('separator midpoint and last 2mm use full seven-bit extent',()=>{const r=C.layout('v'.repeat(15)),lines=C.separators(r).lines;const bottom=28+6*3.95+1.605,next=28+r.rowGroupPitch-1.605;assert.ok(Math.abs(lines[0].y-(bottom+next)/2)<1e-8);assert.ok(Math.abs(lines[1].y-(28+r.rowGroupPitch+6*3.95+1.605+2))<1e-8);assert.equal(lines[0].x1,26);assert.equal(lines[0].x2,274);});
test('separator settings leave holes and PDF unchanged',()=>{const r=C.layout('void'),before=JSON.stringify(r),pdf=C.pdf(r);const on=C.svg(r,{color:'#123456',stroke:.2,length:200,offsetX:-10,offsetY:-.5}),off=C.svg(r,{enabled:false});assert.equal(JSON.stringify(r),before);assert.equal(C.pdf(r),pdf);assert.deepEqual(on.match(/<circle[^>]*>/g),off.match(/<circle[^>]*>/g));assert.ok(on.includes('stroke="#123456" stroke-width="0.2"'));assert.ok(on.includes('x1="16"'));assert.ok(!off.includes('row-group-separators'));assert.ok(!off.includes('<line'));});
test('continuous layout never exports separators',()=>{const r=C.layout('void',{layoutMode:'continuous'});assert.ok(!C.svg(r).includes('<line'));assert.ok(!C.svg(r,{stroke:-1,length:NaN}).includes('row-group-separators'));});
test('separator invalid sizes, bounds and overlaps block SVG only',()=>{const r=C.layout('void'),pdf=C.pdf(r);for(const options of [{stroke:0},{length:-1},{length:Infinity},{offsetX:-30},{offsetY:500},{offsetY:-3},{color:'red"/>'}])assert.throws(()=>C.svg(r,options));assert.equal(C.pdf(r),pdf);assert.ok(!C.svg(r,{enabled:false,length:NaN}).includes('<line'));const dense=C.layout('v'.repeat(15),{rowGroupSpacing:'manual',rowGroupPitch:26.91});assert.throws(()=>C.svg(dense),/간격/);assert.ok(C.svg(dense,{enabled:false}).includes('<circle'));});
console.log(`${count} tests passed`);
